PETASTORM_STORAGE_FOLDER = 'store'
SHADOW_PETASTORM_STORAGE_FOLDER = 'shadow_store'
INPUT_VIDEO_FOLDER = 'data'
TRANSACTION_STORAGE_FOLDER = 'transaction_storage'
BENCHMARK_DATA_FOLDER = 'benchmark_data'
BATCH_SIZE = 50